(function () {
  const meta = document.getElementById("meta");
  const tbody = document.querySelector("#pkgs tbody");
  const empty = document.getElementById("empty");

  function fmtSize(n) {
    if (typeof n !== "number") return "";
    if (n < 1024) return n + " B";
    if (n < 1024 * 1024) return (n / 1024).toFixed(1) + " KiB";
    return (n / (1024 * 1024)).toFixed(2) + " MiB";
  }

  fetch("catalog.json", { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (data) {
      const pkgs = (data && data.packages) || [];
      meta.textContent = data.generated_at
        ? "Generated " + data.generated_at + " · " + pkgs.length + " package(s)"
        : pkgs.length + " package(s) (catalog not yet generated by rebuild)";
      tbody.innerHTML = "";
      if (!pkgs.length) {
        empty.hidden = false;
        return;
      }
      empty.hidden = true;
      pkgs.forEach(function (p) {
        const tr = document.createElement("tr");
        [
          p.name || "",
          p.format || "",
          p.arch || "",
          p.file || "",
          fmtSize(p.size),
          p.key || "",
        ].forEach(function (text) {
          const td = document.createElement("td");
          td.textContent = text;
          tr.appendChild(td);
        });
        tbody.appendChild(tr);
      });
    })
    .catch(function (err) {
      meta.textContent = "Failed to load catalog.json: " + err.message;
    });
})();
